### ISSUE TITLE
gulp uglify and minifyCss not working with Node 6

### ISSUE THREAD

**Issue by shuai-zh** [aeldar/es6-express-scaffold-app#1]
Firstly, nice job for a great example!

I tried to run the default gulp task, but got errors with 'html:build' step. Comment out the following lines solves the issue.

```
 .pipe($.if('*.js', $.uglify()))
 .pipe($.if('*.css', $.minifyCss({compatibility: '*'})))
```

I noticed gulp-minify-css has been deprecated and should be replace with gulp-clean-css, however replacing it with gulp-clean-css doesn't help either.

It would be great if you can take a look and fix this.

Thanks and great job again!

**Comment by aeldar** [comment]
Thank you @shuai-zh for your report. The problem was related to the outdated version of gulp-match plugin (witch is in use by gulp-if) and described here: https://github.com/robrich/gulp-match/issues/12
I've updated gulp-if to the version 2.0.1 (package.json as well) and it fixes the problem for me.

**Comment by aeldar** [comment]
In additions, I replaced gulp-minify-css with the recommended one gulp-clean-css.

**Comment by shuai-zh** [comment]
@aeldar Thank you so much for the quick action, I will give it a try!

**Comment by shuai-zh** [comment]
@aeldar It works like a charm now! Thanks!
